# End-to-End Pandas Data Analysis Practice Project

### A comprehensive hands-on project covering data cleaning, transformation, and analysis using Pandas.

### Section A: Data Loading & Inspection (1–10)

* Developed a clear understanding of dataset structure through loading, inspection, and basic exploration.
* This forms the foundation for effective data manipulation and analysis.

In [2]:
# Load the CSV file into a Pandas DataFrame.
import pandas as pd

df = pd.read_csv(r"C:\Users\hp\Downloads\employee_pandas_practice (1).csv")
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [3]:
# Display the first 7 rows of the DataFrame.

df.head(7)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single

In [4]:
# Display the last 5 rows of the DataFrame.

df.tail()

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [5]:
# Check the shape of the DataFrame.

df.shape

(20, 15)

In [7]:
# Print column names as a Python list.

df.columns.tolist()

['id',
 'name',
 'age',
 'gender',
 'city',
 'salary',
 'department',
 'experience',
 'rating',
 'is_active',
 'projects',
 'leaves_taken',
 'bonus_percent',
 'education',
 'marital_status']

In [8]:
# Display data types of all columns.

df.dtypes

id                  int64
name               object
age               float64
gender             object
city               object
salary            float64
department         object
experience          int64
rating            float64
is_active            bool
projects          float64
leaves_taken      float64
bonus_percent     float64
education          object
marital_status     object
dtype: object

In [9]:
# Show complete DataFrame information.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              20 non-null     int64
 1   name            20 non-null     object
 2   age             19 non-null     float64
 3   gender          20 non-null     object
 4   city            20 non-null     object
 5   salary          19 non-null     float64
 6   department      20 non-null     object
 7   experience      20 non-null     int64
 8   rating          19 non-null     float64
 9   is_active       20 non-null     bool
 10  projects        19 non-null     float64
 11  leaves_taken    19 non-null     float64
 12  bonus_percent   18 non-null     float64
 13  education       20 non-null     object
 14  marital_status  20 non-null     object
dtypes: bool(1), float64(6), int64(2), object(6)
memory usage: 2.3+ KB

In [10]:
# Display summary statistics for numeric columns.

df.describe()

,id,age,salary,experience,rating,projects,leaves_taken,bonus_percent
count,20.00000,19.000000,19.000000,20.000000,19.000000,19.000000,19.000000,18.000000
mean,10.50000,38.684211,75526.315789,7.100000,4.305263,6.368421,7.105263,13.055556
std,5.91608,19.032290,46348.161202,4.290749,0.991337,6.084685,3.665071,3.917866
min,1.00000,23.000000,35000.000000,1.000000,3.300000,2.000000,1.000000,7.000000
25%,5.75000,28.500000,50500.000000,3.750000,3.850000,3.500000,4.000000,10.000000
50%,10.50000,34.000000,66000.000000,6.500000,4.100000,5.000000,7.000000,12.500000
75%,15.25000,40.500000,87000.000000,10.250000,4.450000,7.000000,10.000000,15.750000
max,20.00000,110.000000,250000.000000,15.000000,8.000000,30.000000,13.000000,20.000000

In [11]:
# Display summary statistics for categorical columns.

df.describe(include='object')

            name gender   city department education marital_status
count         20     20     20         20        20             20
unique        20      2      5          5         5              2
top     Person_1   Male  Delhi         IT     BTech         Single
freq           1     10      4          4         4             10

In [12]:
# Check total memory usage of the DataFrame.

df.memory_usage(deep=True).sum()

np.int64(8013)

###  Section B: Column Selection & Data Types (11–20)

* Learned to efficiently select and manage columns based on data types and analytical needs.
* Understanding data types ensures accurate transformations and processing.

In [13]:
# Select only numeric columns from the DataFrame.

df.select_dtypes(include='number')

,id,age,salary,experience,rating,projects,leaves_taken,bonus_percent
0,1,25.0,45000.0,2,4.2,3.0,5.0,10.0
1,2,32.0,55000.0,5,3.8,5.0,10.0,12.0
2,3,41.0,NaN,8,4.5,6.0,7.0,15.0
3,4,29.0,60000.0,3,NaN,4.0,3.0,9.0
4,5,36.0,250000.0,10,4.8,7.0,12.0,18.0
5,6,27.0,50000.0,4,4.1,2.0,6.0,NaN
6,7,45.0,92000.0,11,3.9,8.0,8.0,14.0
7,8,52.0,67000.0,6,4.3,5.0,4.0,10.0
8,9,NaN,48000.0,2,3.5,3.0,2.0,8.0
9,10,28.0,90000.0,12,8.0,30.0,11.0,17.0
10,11,40.0,76000.0,7,4.4,6.0,9.0,16.0
11,12,34.0,51000.0,5,3.7,4.0,NaN,12.0
12,13,23.0,35000.0,1,3.3,2.0,1.0,7.0
13,14,110.0,98000.0,15,4.9,8.0,13.0,20.0
14,15,37.0,66000.0,9,4.0,5.0,7.0,13.0
15,16,26.0,43000.0,3,3.6,3.0,3.0,9.0
16,17,48.0,95000.0,14,4.6,7.0,12.0,19.0
17,18,39.0,72000.0,8,4.1,NaN,8.0,15.0
18,19,30.0,58000.0,4,3.9,4.0,4.0,11.0
19,20,33.0,84000.0,13,4.2,9.0,10.0,NaN

In [14]:
# Select only categorical (object) columns.

df.select_dtypes(include='object')

         name  gender       city department education marital_status
0    Person_1    Male      Delhi         IT     BTech         Single
1    Person_2  Female     Mumbai         HR       MBA        Married
2    Person_3    Male    Kolkata    Finance       MCA         Single
3    Person_4  Female    Chennai  Marketing       BSc        Married
4    Person_5    Male  Bangalore      Admin        BA         Single
5    Person_6  Female      Delhi         IT     BTech        Married
6    Person_7    Male     Mumbai         HR       MBA         Single
7    Person_8  Female    Kolkata    Finance       MCA        Married
8    Person_9    Male    Chennai  Marketing       BSc         Single
9   Person_10  Female  Bangalore      Admin        BA        Married
10  Person_11    Male      Delhi         IT     BTech         Single
11  Person_12  Female     Mumbai         HR       MBA        Married
12  Person_13    Male    Kolkata    Finance       MCA         Single
13  Person_14  Female    Chennai  Marketing       BSc        Married
14  Person_15    Male  Bangalore      Admin        BA         Single
15  Person_16  Female      Delhi         IT     BTech        Married
16  Person_17    Male     Mumbai         HR       MBA         Single
17  Person_18  Female    Kolkata    Finance       MCA        Married
18  Person_19    Male    Chennai  Marketing       BSc         Single
19  Person_20  Female  Bangalore      Admin        BA        Married

In [15]:
# Select boolean columns only.

df.select_dtypes(include='bool')

    is_active
0        True
1       False
2        True
3        True
4       False
5        True
6       False
7        True
8       False
9        True
10       True
11      False
12       True
13       True
14      False
15       True
16      False
17       True
18      False
19       True

In [16]:
# Select all columns except numeric ones.

df.select_dtypes(exclude='number')

,name,gender,city,department,is_active,education,marital_status
0,Person_1,Male,Delhi,IT,True,BTech,Single
1,Person_2,Female,Mumbai,HR,False,MBA,Married
2,Person_3,Male,Kolkata,Finance,True,MCA,Single
3,Person_4,Female,Chennai,Marketing,True,BSc,Married
4,Person_5,Male,Bangalore,Admin,False,BA,Single
5,Person_6,Female,Delhi,IT,True,BTech,Married
6,Person_7,Male,Mumbai,HR,False,MBA,Single
7,Person_8,Female,Kolkata,Finance,True,MCA,Married
8,Person_9,Male,Chennai,Marketing,False,BSc,Single
9,Person_10,Female,Bangalore,Admin,True,BA,Married
10,Person_11,Male,Delhi,IT,True,BTech,Single
11,Person_12,Female,Mumbai,HR,False,MBA,Married
12,Person_13,Male,Kolkata,Finance,True,MCA,Single
13,Person_14,Female,Chennai,Marketing,True,BSc,Married
14,Person_15,Male,Bangalore,Admin,False,BA,Single
15,Person_16,Female,Delhi,IT,True,BTech,Married
16,Person_17,Male,Mumbai,HR,False,MBA,Single
17,Person_18,Female,Kolkata,Finance,True,MCA,Married
18,Person_19,Male,Chennai,Marketing,False,BSc,Single
19,Person_20,Female,Bangalore,Admin,True,BA,Married

In [17]:
# Select the name, city, and salary columns.

df[['name', 'city', 'salary']]

         name       city    salary
0    Person_1      Delhi   45000.0
1    Person_2     Mumbai   55000.0
2    Person_3    Kolkata       NaN
3    Person_4    Chennai   60000.0
4    Person_5  Bangalore  250000.0
5    Person_6      Delhi   50000.0
6    Person_7     Mumbai   92000.0
7    Person_8    Kolkata   67000.0
8    Person_9    Chennai   48000.0
9   Person_10  Bangalore   90000.0
10  Person_11      Delhi   76000.0
11  Person_12     Mumbai   51000.0
12  Person_13    Kolkata   35000.0
13  Person_14    Chennai   98000.0
14  Person_15  Bangalore   66000.0
15  Person_16      Delhi   43000.0
16  Person_17     Mumbai   95000.0
17  Person_18    Kolkata   72000.0
18  Person_19    Chennai   58000.0
19  Person_20  Bangalore   84000.0

In [18]:
# Select the first 5 columns using positional indexing.

df.iloc[:, :5]

    id       name    age  gender       city
0    1   Person_1   25.0    Male      Delhi
1    2   Person_2   32.0  Female     Mumbai
2    3   Person_3   41.0    Male    Kolkata
3    4   Person_4   29.0  Female    Chennai
4    5   Person_5   36.0    Male  Bangalore
5    6   Person_6   27.0  Female      Delhi
6    7   Person_7   45.0    Male     Mumbai
7    8   Person_8   52.0  Female    Kolkata
8    9   Person_9    NaN    Male    Chennai
9   10  Person_10   28.0  Female  Bangalore
10  11  Person_11   40.0    Male      Delhi
11  12  Person_12   34.0  Female     Mumbai
12  13  Person_13   23.0    Male    Kolkata
13  14  Person_14  110.0  Female    Chennai
14  15  Person_15   37.0    Male  Bangalore
15  16  Person_16   26.0  Female      Delhi
16  17  Person_17   48.0    Male     Mumbai
17  18  Person_18   39.0  Female    Kolkata
18  19  Person_19   30.0    Male    Chennai
19  20  Person_20   33.0  Female  Bangalore

In [19]:
# Select alternate columns (every second column).

df.iloc[:, ::2]

,id,age,city,department,rating,projects,bonus_percent,marital_status
0,1,25.0,Delhi,IT,4.2,3.0,10.0,Single
1,2,32.0,Mumbai,HR,3.8,5.0,12.0,Married
2,3,41.0,Kolkata,Finance,4.5,6.0,15.0,Single
3,4,29.0,Chennai,Marketing,NaN,4.0,9.0,Married
4,5,36.0,Bangalore,Admin,4.8,7.0,18.0,Single
5,6,27.0,Delhi,IT,4.1,2.0,NaN,Married
6,7,45.0,Mumbai,HR,3.9,8.0,14.0,Single
7,8,52.0,Kolkata,Finance,4.3,5.0,10.0,Married
8,9,NaN,Chennai,Marketing,3.5,3.0,8.0,Single
9,10,28.0,Bangalore,Admin,8.0,30.0,17.0,Married
10,11,40.0,Delhi,IT,4.4,6.0,16.0,Single
11,12,34.0,Mumbai,HR,3.7,4.0,12.0,Married
12,13,23.0,Kolkata,Finance,3.3,2.0,7.0,Single
13,14,110.0,Chennai,Marketing,4.9,8.0,20.0,Married
14,15,37.0,Bangalore,Admin,4.0,5.0,13.0,Single
15,16,26.0,Delhi,IT,3.6,3.0,9.0,Married
16,17,48.0,Mumbai,HR,4.6,7.0,19.0,Single
17,18,39.0,Kolkata,Finance,4.1,NaN,15.0,Married
18,19,30.0,Chennai,Marketing,3.9,4.0,11.0,Single
19,20,33.0,Bangalore,Admin,4.2,9.0,NaN,Married

In [21]:
# Convert department column to category data type.

df['department'] = df['department'].astype('category')
df['department']

0            IT
1            HR
2       Finance
3     Marketing
4         Admin
5            IT
6            HR
7       Finance
8     Marketing
9         Admin
10           IT
11           HR
12      Finance
13    Marketing
14        Admin
15           IT
16           HR
17      Finance
18    Marketing
19        Admin
Name: department, dtype: category
Categories (5, object): ['Admin', 'Finance', 'HR', 'IT', 'Marketing']

In [23]:
# Convert salary column to float explicitly.

df['salary'] = df['salary'].astype(float)
df['salary']

0      45000.0
1      55000.0
2          NaN
3      60000.0
4     250000.0
5      50000.0
6      92000.0
7      67000.0
8      48000.0
9      90000.0
10     76000.0
11     51000.0
12     35000.0
13     98000.0
14     66000.0
15     43000.0
16     95000.0
17     72000.0
18     58000.0
19     84000.0
Name: salary, dtype: float64

In [24]:
# Select columns whose data type is float.

df.select_dtypes(include='float')

      age    salary  rating  projects  leaves_taken  bonus_percent
0    25.0   45000.0     4.2       3.0           5.0           10.0
1    32.0   55000.0     3.8       5.0          10.0           12.0
2    41.0       NaN     4.5       6.0           7.0           15.0
3    29.0   60000.0     NaN       4.0           3.0            9.0
4    36.0  250000.0     4.8       7.0          12.0           18.0
5    27.0   50000.0     4.1       2.0           6.0            NaN
6    45.0   92000.0     3.9       8.0           8.0           14.0
7    52.0   67000.0     4.3       5.0           4.0           10.0
8     NaN   48000.0     3.5       3.0           2.0            8.0
9    28.0   90000.0     8.0      30.0          11.0           17.0
10   40.0   76000.0     4.4       6.0           9.0           16.0
11   34.0   51000.0     3.7       4.0           NaN           12.0
12   23.0   35000.0     3.3       2.0           1.0            7.0
13  110.0   98000.0     4.9       8.0          13.0           20.0
14   37.0   66000.0     4.0       5.0           7.0           13.0
15   26.0   43000.0     3.6       3.0           3.0            9.0
16   48.0   95000.0     4.6       7.0          12.0           19.0
17   39.0   72000.0     4.1       NaN           8.0           15.0
18   30.0   58000.0     3.9       4.0           4.0           11.0
19   33.0   84000.0     4.2       9.0          10.0            NaN

### Section C: Missing Value Analysis (21–35)

* Applied multiple techniques to identify and handle missing data systematically.
* This step improves data quality and ensures reliable downstream analysis.

In [25]:
# Count missing values in each column.

df.isnull().sum()

id                0
name              0
age               1
gender            0
city              0
salary            1
department        0
experience        0
rating            1
is_active         0
projects          1
leaves_taken      1
bonus_percent     2
education         0
marital_status    0
dtype: int64

In [26]:
# Find total number of missing values in the DataFrame.

df.isnull().sum().sum()

np.int64(7)

In [27]:
# Identify rows where salary is missing.

df[df['salary'].isnull()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single

In [28]:
# Identify rows having at least one missing value.

df[df.isnull().any(axis=1)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [29]:
# Identify rows where all values are present.

df[df.notnull().all(axis=1)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single

In [31]:
# Fill missing age values with the column mean.

df['age'] = df['age'].fillna(df['age'].mean())
df['age']

0      25.000000
1      32.000000
2      41.000000
3      29.000000
4      36.000000
5      27.000000
6      45.000000
7      52.000000
8      38.684211
9      28.000000
10     40.000000
11     34.000000
12     23.000000
13    110.000000
14     37.000000
15     26.000000
16     48.000000
17     39.000000
18     30.000000
19     33.000000
Name: age, dtype: float64

In [33]:
# Fill missing salary values with the column median.

df['salary'] = df['salary'].fillna(df['salary'].median())
df['salary']

0      45000.0
1      55000.0
2      66000.0
3      60000.0
4     250000.0
5      50000.0
6      92000.0
7      67000.0
8      48000.0
9      90000.0
10     76000.0
11     51000.0
12     35000.0
13     98000.0
14     66000.0
15     43000.0
16     95000.0
17     72000.0
18     58000.0
19     84000.0
Name: salary, dtype: float64

In [35]:
# Fill missing categorical values with "Unknown".

df = df.fillna({'column_name': 'Unknown'})
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [36]:
# Forward-fill missing values.

df = df.ffill()
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married

In [38]:
# Backward-fill missing values.

df = df.bfill()
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married

In [49]:
# Fill missing bonus_percent using department-wise mean.

df['bonus_percent'] = df['bonus_percent'].fillna(
    df.groupby('department', observed=True)['bonus_percent'].transform('mean'))
df['bonus_percent']

0     10.0
1     12.0
2     15.0
3      9.0
4     18.0
5     18.0
6     14.0
7     10.0
8      8.0
9     17.0
10    16.0
11    12.0
12     7.0
13    20.0
14    13.0
15     9.0
16    19.0
17    15.0
18    11.0
19    11.0
Name: bonus_percent, dtype: float64

In [55]:
# Drop rows where rating is missing.

df = df.dropna(subset=['rating'])
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married

In [57]:
# Drop columns having more than 2 missing values.

df = df.dropna(axis=1, thresh=len(df) - 2)
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married

In [59]:
# Create a new column indicating whether salary was missing.

df['salary_was_missing'] = df['salary'].isnull()
df['salary_was_missing']

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: salary_was_missing, dtype: bool

In [63]:
# Replace all remaining missing values with 0.

# Numeric columns → fill with 0
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(0)

# Categorical columns → pehle category add karo, phir fill karo
cat_cols = df.select_dtypes(include='category').columns
for col in cat_cols:
    df[col] = df[col].cat.add_categories('Unknown').fillna('Unknown')

# Object columns → fill with 'Unknown'
obj_cols = df.select_dtypes(include='object').columns
df[obj_cols] = df[obj_cols].fillna('Unknown')

###  Section D: Outlier Detection & Treatment (36–50)

* Identified and treated outliers using statistical methods such as IQR.
* This enhances data consistency and minimizes the impact of anomalies.

In [64]:
# Detect outliers in age using the IQR method.

Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['age'] < lower) | (df['age'] > upper)]
outliers

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False

In [65]:
# Detect outliers in salary using the IQR method.

Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['salary'] < lower) | (df['salary'] > upper)]
outliers

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single,False

In [66]:
# Identify rows where projects is an outlier.

Q1 = df['projects'].quantile(0.25)
Q3 = df['projects'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[(df['projects'] < lower) | (df['projects'] > upper)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,False

In [68]:
# Create a new column flagging salary outliers.

Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df['salary_outlier'] = ((df['salary'] < lower) | (df['salary'] > upper))
df['salary_outlier']

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: salary_outlier, dtype: bool

In [70]:
# Remove rows containing salary outliers.

df = df[~df['salary_outlier']]
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,False,False
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False

In [73]:
# Cap salary outliers using upper and lower IQR limits.

Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df['salary'] = df['salary'].clip(lower, upper)
df['salary']

0     45000.0
1     55000.0
2     66000.0
3     60000.0
5     50000.0
6     92000.0
7     67000.0
8     48000.0
9     90000.0
10    76000.0
11    51000.0
12    35000.0
13    98000.0
14    66000.0
15    43000.0
16    95000.0
17    72000.0
18    58000.0
19    84000.0
Name: salary, dtype: float64

In [75]:
# Replace age outliers with median age.

Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

median_age = df['age'].median()

df.loc[(df['age'] < lower) | (df['age'] > upper), 'age'] = median_age

In [76]:
# Detect outliers in rating.

Q1 = df['rating'].quantile(0.25)
Q3 = df['rating'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[(df['rating'] < lower) | (df['rating'] > upper)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,False,False

In [78]:
# Detect department-wise salary outliers.

def detect_outliers(group):
    Q1 = group['salary'].quantile(0.25)
    Q3 = group['salary'].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return group[(group['salary'] < lower) | (group['salary'] > upper)]

df.groupby('department', observed=True, group_keys=False)\
  .apply(detect_outliers, include_groups=False)

,id,name,age,gender,city,salary,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier
12,13,Person_13,23.0,Male,Kolkata,35000.0,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False
10,11,Person_11,40.0,Male,Delhi,76000.0,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False
13,14,Person_14,34.0,Female,Chennai,98000.0,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False

In [80]:
# Count number of outliers in each numeric column.

num_cols = df.select_dtypes(include='number').columns

outlier_counts = {}

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outlier_counts[col] = ((df[col] < lower) | (df[col] > upper)).sum()

outlier_counts

{'id': np.int64(0),
 'age': np.int64(0),
 'salary': np.int64(0),
 'experience': np.int64(0),
 'rating': np.int64(1),
 'projects': np.int64(1),
 'leaves_taken': np.int64(0),
 'bonus_percent': np.int64(0)}

In [81]:
# Identify rows having more than one outlier.

num_cols = df.select_dtypes(include='number').columns

outlier_flag = pd.DataFrame()

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outlier_flag[col] = (df[col] < lower) | (df[col] > upper)

# Rows with more than 1 outlier
df[outlier_flag.sum(axis=1) > 1]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,False,False

In [83]:
# Replace outliers in projects with the 95th percentile.

Q1 = df['projects'].quantile(0.25)
Q3 = df['projects'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

p95 = df['projects'].quantile(0.95)

df.loc[(df['projects'] < lower) | (df['projects'] > upper), 'projects'] = p95

In [85]:
#Normalize salary after outlier treatment.

df['salary'] = (df['salary'] - df['salary'].min()) / (df['salary'].max() - df['salary'].min())
df['salary']

0     0.158730
1     0.317460
2     0.492063
3     0.396825
5     0.238095
6     0.904762
7     0.507937
8     0.206349
9     0.873016
10    0.650794
11    0.253968
12    0.000000
13    1.000000
14    0.492063
15    0.126984
16    0.952381
17    0.587302
18    0.365079
19    0.777778
Name: salary, dtype: float64

In [87]:
# Compare salary before and after capping.

# Step 1: Original salary save karo
df['salary_before'] = df['salary']

# Step 2: Capping karo
Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df['salary'] = df['salary'].clip(lower, upper)

# Step 3: Compare
df[['salary_before', 'salary']]

    salary_before    salary
0        0.158730  0.158730
1        0.317460  0.317460
2        0.492063  0.492063
3        0.396825  0.396825
5        0.238095  0.238095
6        0.904762  0.904762
7        0.507937  0.507937
8        0.206349  0.206349
9        0.873016  0.873016
10       0.650794  0.650794
11       0.253968  0.253968
12       0.000000  0.000000
13       1.000000  1.000000
14       0.492063  0.492063
15       0.126984  0.126984
16       0.952381  0.952381
17       0.587302  0.587302
18       0.365079  0.365079
19       0.777778  0.777778

In [88]:
#Create a clean DataFrame with no outliers.

num_cols = df.select_dtypes(include='number').columns

clean_df = df.copy()

for col in num_cols:
    Q1 = clean_df[col].quantile(0.25)
    Q3 = clean_df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    clean_df = clean_df[(clean_df[col] >= lower) & (clean_df[col] <= upper)]

clean_df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778

### Section E: Filtering & Conditional Selection (51–70)

* Utilized filtering techniques to extract meaningful subsets of data.
* This enables targeted analysis and supports decision-making scenarios.

In [90]:
# Filter employees whose salary is greater than 60,000.

df[df['salary'] > 60000]

Empty DataFrame
Columns: [id, name, age, gender, city, salary, department, experience, rating, is_active, projects, leaves_taken, bonus_percent, education, marital_status, salary_was_missing, salary_outlier, salary_before]
Index: []

In [91]:
# Filter employees whose age is less than 30.

df[df['age'] < 30]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
0,1,Person_1,25.0,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
3,4,Person_4,29.0,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
5,6,Person_6,27.0,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
9,10,Person_10,28.0,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
12,13,Person_13,23.0,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
15,16,Person_16,26.0,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984

In [92]:
# Filter employees from Delhi or Mumbai.

df[df['city'].isin(['Delhi', 'Mumbai'])]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
0,1,Person_1,25.0,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
1,2,Person_2,32.0,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
5,6,Person_6,27.0,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
6,7,Person_7,45.0,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
10,11,Person_11,40.0,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
11,12,Person_12,34.0,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
15,16,Person_16,26.0,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
16,17,Person_17,48.0,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381

In [93]:
# Filter employees from IT department with salary > 70,000.

df[(df['department'] == 'IT') & (df['salary'] > 70000)]

Empty DataFrame
Columns: [id, name, age, gender, city, salary, department, experience, rating, is_active, projects, leaves_taken, bonus_percent, education, marital_status, salary_was_missing, salary_outlier, salary_before]
Index: []

In [94]:
# Filter employees with more than 10 years of experience.

df[df['experience'] > 10]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
6,7,Person_7,45.0,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
9,10,Person_10,28.0,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
13,14,Person_14,34.0,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
16,17,Person_17,48.0,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
19,20,Person_20,33.0,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778

In [95]:
# Filter employees who are active.

df[df['is_active'] == True]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
0,1,Person_1,25.0,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
2,3,Person_3,41.0,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
3,4,Person_4,29.0,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
5,6,Person_6,27.0,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
7,8,Person_8,52.0,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
9,10,Person_10,28.0,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
10,11,Person_11,40.0,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
12,13,Person_13,23.0,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
13,14,Person_14,34.0,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
15,16,Person_16,26.0,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
17,18,Person_18,39.0,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
19,20,Person_20,33.0,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778

In [96]:
# Filter employees who are inactive and married.

df[(df['is_active'] == False) & (df['marital_status'] == 'Married')]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
1,2,Person_2,32.0,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
11,12,Person_12,34.0,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968

In [97]:
# Filter employees whose projects count is between 3 and 7.

df[(df['projects'] >= 3) & (df['projects'] <= 7)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079

In [98]:
# Filter employees whose salary is missing.

df[df['salary'].isnull()]

Empty DataFrame
Columns: [id, name, age, gender, city, salary, department, experience, rating, is_active, projects, leaves_taken, bonus_percent, education, marital_status, salary_was_missing, salary_outlier, salary_before]
Index: []

In [99]:
# Filter employees with no missing values.

df[df.notnull().all(axis=1)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778

In [100]:
# Filter employees whose rating is above average.

df[df['rating'] > df['rating'].mean()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
2,3,Person_3,41.0,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
3,4,Person_4,29.0,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
7,8,Person_8,52.0,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
9,10,Person_10,28.0,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
10,11,Person_11,40.0,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
13,14,Person_14,34.0,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
16,17,Person_17,48.0,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381

In [101]:
# Filter top 5 highest-paid employees.

df.nlargest(5, 'salary')

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
13,14,Person_14,34.0,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
16,17,Person_17,48.0,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
6,7,Person_7,45.0,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
9,10,Person_10,28.0,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
19,20,Person_20,33.0,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778

In [102]:
# Filter bottom 5 employees by rating.

df.nsmallest(5, 'rating')

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460

In [103]:
# Filter employees whose city is not Bangalore.

df[df['city'] != 'Bangalore']

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079

In [104]:
# Filter employees whose bonus percent is greater than 15.

df[df['bonus_percent'] > 15]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
5,6,Person_6,27.0,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
9,10,Person_10,28.0,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
10,11,Person_11,40.0,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
13,14,Person_14,34.0,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
16,17,Person_17,48.0,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381

In [105]:
# Filter employees using query() method.

df.query("salary > 60000 and age < 30")

Empty DataFrame
Columns: [id, name, age, gender, city, salary, department, experience, rating, is_active, projects, leaves_taken, bonus_percent, education, marital_status, salary_was_missing, salary_outlier, salary_before]
Index: []

In [107]:
# Filter employees using lambda function.

df[lambda x: (x['salary'] > 50000) & (x['age'] < 40)]

Empty DataFrame
Columns: [id, name, age, gender, city, salary, department, experience, rating, is_active, projects, leaves_taken, bonus_percent, education, marital_status, salary_was_missing, salary_outlier, salary_before]
Index: []

In [113]:
# Filter rows where salary is above department average.

df[df['salary'] > df.groupby('department', observed=True)['salary'].transform('mean')]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
2,3,Person_3,41.0,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
6,7,Person_7,45.0,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
7,8,Person_8,52.0,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
9,10,Person_10,28.0,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
10,11,Person_11,40.0,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
13,14,Person_14,34.0,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
16,17,Person_17,48.0,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
17,18,Person_18,39.0,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
19,20,Person_20,33.0,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778

In [114]:
# Filter employees with maximum experience.

df[df['experience'] == df['experience'].max()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
13,14,Person_14,34.0,Female,Chennai,1.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.0

In [115]:
# Filter employees whose projects count is an outlier.

Q1 = df['projects'].quantile(0.25)
Q3 = df['projects'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[(df['projects'] < lower) | (df['projects'] > upper)]

Empty DataFrame
Columns: [id, name, age, gender, city, salary, department, experience, rating, is_active, projects, leaves_taken, bonus_percent, education, marital_status, salary_was_missing, salary_outlier, salary_before]
Index: []

### Section F: value_counts, unique, nunique (71–85)

* Analyzed categorical variables using frequency distributions and unique counts.
* This provides insights into data patterns and category-level trends.

In [119]:
# Find unique cities.

df['city'].unique()

array(['Delhi', 'Mumbai', 'Kolkata', 'Chennai', 'Bangalore'], dtype=object)

In [120]:
# Count number of unique departments.

df['department'].nunique()

5

In [121]:
# Find frequency of each department.

df['department'].value_counts()

department
Finance      4
HR           4
Marketing    4
IT           4
Admin        3
Unknown      0
Name: count, dtype: int64

In [122]:
# Find city-wise employee count.

df['city'].value_counts()

city
Delhi        4
Mumbai       4
Kolkata      4
Chennai      4
Bangalore    3
Name: count, dtype: int64

In [123]:
#Find education-wise distribution.

df['education'].value_counts()

education
BTech    4
MBA      4
MCA      4
BSc      4
BA       3
Name: count, dtype: int64

In [124]:
# Calculate percentage distribution of gender.

df['gender'].value_counts(normalize=True) * 100

gender
Female    52.631579
Male      47.368421
Name: proportion, dtype: float64

In [125]:
# Sort department counts in ascending order.

df['department'].value_counts().sort_values(ascending=True)

department
Unknown      0
Admin        3
Finance      4
HR           4
IT           4
Marketing    4
Name: count, dtype: int64

In [126]:
# Identify departments having more than 3 employees.

df['department'].value_counts()[df['department'].value_counts() > 3]

department
Finance      4
HR           4
Marketing    4
IT           4
Name: count, dtype: int64

In [127]:
# Convert value_counts output to DataFrame.

df['department'].value_counts().reset_index(name='count')

  department  count
0    Finance      4
1         HR      4
2  Marketing      4
3         IT      4
4      Admin      3
5    Unknown      0

In [128]:
# Find rare education categories.

df['education'].value_counts()[df['education'].value_counts() < 2]

Series([], Name: count, dtype: int64)

In [129]:
# Count unique cities per department.

df.groupby('department', observed=True)['city'].nunique()

department
Admin        1
Finance      1
HR           1
IT           1
Marketing    1
Name: city, dtype: int64

In [130]:
# Find most common city.

df['city'].value_counts().idxmax()

'Delhi'

In [131]:
# Find least common department.

df['department'].value_counts().idxmin()

'Unknown'

In [132]:
# Find number of unique marital statuses.

df['marital_status'].nunique()

2

In [134]:
# Merge rare education values into "Other".

rare = df['education'].value_counts()[df['education'].value_counts() < 2].index

df['education'] = df['education'].replace(rare, 'Other')
df ['education']

0     BTech
1       MBA
2       MCA
3       BSc
5     BTech
6       MBA
7       MCA
8       BSc
9        BA
10    BTech
11      MBA
12      MCA
13      BSc
14       BA
15    BTech
16      MBA
17      MCA
18      BSc
19       BA
Name: education, dtype: object

### Section G: Sorting & Ranking (86–100)

* Applied sorting and ranking to identify trends, extremes, and performance metrics.
* This improves interpretability and comparative analysis.

In [135]:
# Sort employees by salary ascending.

df.sort_values(by='salary', ascending=True)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000

In [136]:
# Sort employees by salary descending

df.sort_values(by='salary', ascending=False)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000

In [137]:
# Sort employees by city and salary.

df.sort_values(by=['city', 'salary'])

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381

In [138]:
# Sort employees by experience descending.

df.sort_values(by='experience', ascending=False)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000

In [139]:
# Sort employees placing missing salary at the end.

df.sort_values(by='salary', na_position='last')

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000

In [141]:
# Rank employees based on salary.

df['salary_rank'] = df['salary'].rank()
df['salary_rank']

0      3.0
1      7.0
2     10.5
3      9.0
5      5.0
6     17.0
7     12.0
8      4.0
9     16.0
10    14.0
11     6.0
12     1.0
13    19.0
14    10.5
15     2.0
16    18.0
17    13.0
18     8.0
19    15.0
Name: salary_rank, dtype: float64

In [142]:
# Rank employees department-wise by salary.

df['dept_salary_rank'] = df.groupby('department', observed=True)['salary'].rank()
df['dept_salary_rank']

0     2.0
1     2.0
2     2.0
3     3.0
5     3.0
6     3.0
7     3.0
8     1.0
9     3.0
10    4.0
11    1.0
12    1.0
13    4.0
14    1.0
15    1.0
16    4.0
17    4.0
18    2.0
19    2.0
Name: dept_salary_rank, dtype: float64

In [144]:
# Rank employees based on experience.

df['experience_rank'] = df['experience'].rank()
df['experience_rank']

0      2.5
1      8.5
2     12.5
3      4.5
5      6.5
6     15.0
7     10.0
8      2.5
9     16.0
10    11.0
11     8.5
12     1.0
13    19.0
14    14.0
15     4.5
16    18.0
17    12.5
18     6.5
19    17.0
Name: experience_rank, dtype: float64

In [145]:
# Sort departments by average salary.

df.groupby('department', observed=True)['salary'].mean().sort_values()

department
IT           0.293651
Finance      0.396825
Marketing    0.492063
HR           0.607143
Admin        0.714286
Name: salary, dtype: float64

In [146]:
# Sort employees by number of projects.

df.sort_values(by='projects')

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before,salary_rank,dept_salary_rank,experience_rank
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,...,6.0,18.0,BTech,Married,False,False,0.238095,5.0,3.0,6.5
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,...,1.0,7.0,MCA,Single,False,False,0.000000,1.0,1.0,1.0
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,...,2.0,8.0,BSc,Single,False,False,0.206349,4.0,1.0,2.5
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,...,5.0,10.0,BTech,Single,False,False,0.158730,3.0,2.0,2.5
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,...,3.0,9.0,BTech,Married,False,False,0.126984,2.0,1.0,4.5
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,...,9.0,12.0,MBA,Married,False,False,0.253968,6.0,1.0,8.5
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,...,3.0,9.0,BSc,Married,False,False,0.396825,9.0,3.0,4.5
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,...,4.0,11.0,BSc,Single,False,False,0.365079,8.0,2.0,6.5
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,...,10.0,12.0,MBA,Married,False,False,0.317460,7.0,2.0,8.5
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,...,7.0,13.0,BA,Single,False,False,0.492063,10.5,1.0,14.0
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,...,4.0,10.0,MCA,Married,False,False,0.507937,12.0,3.0,10.0
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,...,9.0,16.0,BTech,Single,False,False,0.650794,14.0,4.0,11.0
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,...,7.0,15.0,MCA,Single,False,False,0.492063,10.5,2.0,12.5
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,...,12.0,19.0,MBA,Single,False,False,0.952381,18.0,4.0,18.0
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,...,8.0,15.0,MCA,Married,False,False,0.587302,13.0,4.0,12.5
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,...,8.0,14.0,MBA,Single,False,False,0.904762,17.0,3.0,15.0
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,...,13.0,20.0,BSc,Married,False,False,1.000000,19.0,4.0,19.0
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,...,10.0,11.0,BA,Married,False,False,0.777778,15.0,2.0,17.0
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,...,11.0,17.0,BA,Married,False,False,0.873016,16.0,3.0,16.0

In [147]:
# Sort DataFrame by index descending.

df.sort_index(ascending=False)

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before,salary_rank,dept_salary_rank,experience_rank
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,...,10.0,11.0,BA,Married,False,False,0.777778,15.0,2.0,17.0
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,...,4.0,11.0,BSc,Single,False,False,0.365079,8.0,2.0,6.5
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,...,8.0,15.0,MCA,Married,False,False,0.587302,13.0,4.0,12.5
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,...,12.0,19.0,MBA,Single,False,False,0.952381,18.0,4.0,18.0
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,...,3.0,9.0,BTech,Married,False,False,0.126984,2.0,1.0,4.5
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,...,7.0,13.0,BA,Single,False,False,0.492063,10.5,1.0,14.0
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,...,13.0,20.0,BSc,Married,False,False,1.000000,19.0,4.0,19.0
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,...,1.0,7.0,MCA,Single,False,False,0.000000,1.0,1.0,1.0
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,...,9.0,12.0,MBA,Married,False,False,0.253968,6.0,1.0,8.5
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,...,9.0,16.0,BTech,Single,False,False,0.650794,14.0,4.0,11.0
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,...,11.0,17.0,BA,Married,False,False,0.873016,16.0,3.0,16.0
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,...,2.0,8.0,BSc,Single,False,False,0.206349,4.0,1.0,2.5
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,...,4.0,10.0,MCA,Married,False,False,0.507937,12.0,3.0,10.0
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,...,8.0,14.0,MBA,Single,False,False,0.904762,17.0,3.0,15.0
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,...,6.0,18.0,BTech,Married,False,False,0.238095,5.0,3.0,6.5
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,...,3.0,9.0,BSc,Married,False,False,0.396825,9.0,3.0,4.5
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,...,7.0,15.0,MCA,Single,False,False,0.492063,10.5,2.0,12.5
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,...,10.0,12.0,MBA,Married,False,False,0.317460,7.0,2.0,8.5
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,...,5.0,10.0,BTech,Single,False,False,0.158730,3.0,2.0,2.5

In [149]:
# Sort employees by salary-to-experience ratio.

df.assign(ratio=df['salary'] / df['experience']).sort_values(by='ratio', ascending=False)

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before,salary_rank,dept_salary_rank,experience_rank,ratio
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,...,9.0,BSc,Married,False,False,0.396825,9.0,3.0,4.5,0.132275
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,...,8.0,BSc,Single,False,False,0.206349,4.0,1.0,2.5,0.103175
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,...,16.0,BTech,Single,False,False,0.650794,14.0,4.0,11.0,0.092971
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,...,11.0,BSc,Single,False,False,0.365079,8.0,2.0,6.5,0.091270
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,...,10.0,MCA,Married,False,False,0.507937,12.0,3.0,10.0,0.084656
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,...,14.0,MBA,Single,False,False,0.904762,17.0,3.0,15.0,0.082251
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,...,10.0,BTech,Single,False,False,0.158730,3.0,2.0,2.5,0.079365
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,...,15.0,MCA,Married,False,False,0.587302,13.0,4.0,12.5,0.073413
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,...,17.0,BA,Married,False,False,0.873016,16.0,3.0,16.0,0.072751
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,...,19.0,MBA,Single,False,False,0.952381,18.0,4.0,18.0,0.068027
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,...,20.0,BSc,Married,False,False,1.000000,19.0,4.0,19.0,0.066667
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,...,12.0,MBA,Married,False,False,0.317460,7.0,2.0,8.5,0.063492
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,...,15.0,MCA,Single,False,False,0.492063,10.5,2.0,12.5,0.061508
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,...,11.0,BA,Married,False,False,0.777778,15.0,2.0,17.0,0.059829
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,...,18.0,BTech,Married,False,False,0.238095,5.0,3.0,6.5,0.059524
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,...,13.0,BA,Single,False,False,0.492063,10.5,1.0,14.0,0.054674
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,...,12.0,MBA,Married,False,False,0.253968,6.0,1.0,8.5,0.050794
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,...,9.0,BTech,Married,False,False,0.126984,2.0,1.0,4.5,0.042328
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,...,7.0,MCA,Single,False,False,0.000000,1.0,1.0,1.0,0.000000

In [150]:
# Sort employees by bonus percent.

df.sort_values(by='bonus_percent')

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before,salary_rank,dept_salary_rank,experience_rank
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,...,1.0,7.0,MCA,Single,False,False,0.000000,1.0,1.0,1.0
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,...,2.0,8.0,BSc,Single,False,False,0.206349,4.0,1.0,2.5
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,...,3.0,9.0,BTech,Married,False,False,0.126984,2.0,1.0,4.5
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,...,3.0,9.0,BSc,Married,False,False,0.396825,9.0,3.0,4.5
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,...,4.0,10.0,MCA,Married,False,False,0.507937,12.0,3.0,10.0
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,...,5.0,10.0,BTech,Single,False,False,0.158730,3.0,2.0,2.5
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,...,10.0,11.0,BA,Married,False,False,0.777778,15.0,2.0,17.0
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,...,4.0,11.0,BSc,Single,False,False,0.365079,8.0,2.0,6.5
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,...,10.0,12.0,MBA,Married,False,False,0.317460,7.0,2.0,8.5
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,...,9.0,12.0,MBA,Married,False,False,0.253968,6.0,1.0,8.5
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,...,7.0,13.0,BA,Single,False,False,0.492063,10.5,1.0,14.0
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,...,8.0,14.0,MBA,Single,False,False,0.904762,17.0,3.0,15.0
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,...,7.0,15.0,MCA,Single,False,False,0.492063,10.5,2.0,12.5
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,...,8.0,15.0,MCA,Married,False,False,0.587302,13.0,4.0,12.5
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,...,9.0,16.0,BTech,Single,False,False,0.650794,14.0,4.0,11.0
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,...,11.0,17.0,BA,Married,False,False,0.873016,16.0,3.0,16.0
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,...,6.0,18.0,BTech,Married,False,False,0.238095,5.0,3.0,6.5
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,...,12.0,19.0,MBA,Single,False,False,0.952381,18.0,4.0,18.0
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,...,13.0,20.0,BSc,Married,False,False,1.000000,19.0,4.0,19.0

In [151]:
# Sort employees by frequency of city.

df.sort_values(by='city', key=lambda x: x.map(x.value_counts()))

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before,salary_rank,dept_salary_rank,experience_rank
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,...,7.0,13.0,BA,Single,False,False,0.492063,10.5,1.0,14.0
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,...,11.0,17.0,BA,Married,False,False,0.873016,16.0,3.0,16.0
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,...,10.0,11.0,BA,Married,False,False,0.777778,15.0,2.0,17.0
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,...,5.0,10.0,BTech,Single,False,False,0.158730,3.0,2.0,2.5
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,...,6.0,18.0,BTech,Married,False,False,0.238095,5.0,3.0,6.5
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,...,8.0,14.0,MBA,Single,False,False,0.904762,17.0,3.0,15.0
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,...,7.0,15.0,MCA,Single,False,False,0.492063,10.5,2.0,12.5
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,...,10.0,12.0,MBA,Married,False,False,0.317460,7.0,2.0,8.5
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,...,2.0,8.0,BSc,Single,False,False,0.206349,4.0,1.0,2.5
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,...,4.0,10.0,MCA,Married,False,False,0.507937,12.0,3.0,10.0
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,...,9.0,12.0,MBA,Married,False,False,0.253968,6.0,1.0,8.5
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,...,9.0,16.0,BTech,Single,False,False,0.650794,14.0,4.0,11.0
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,...,1.0,7.0,MCA,Single,False,False,0.000000,1.0,1.0,1.0
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,...,13.0,20.0,BSc,Married,False,False,1.000000,19.0,4.0,19.0
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,...,3.0,9.0,BTech,Married,False,False,0.126984,2.0,1.0,4.5
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,...,3.0,9.0,BSc,Married,False,False,0.396825,9.0,3.0,4.5
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,...,12.0,19.0,MBA,Single,False,False,0.952381,18.0,4.0,18.0
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,...,8.0,15.0,MCA,Married,False,False,0.587302,13.0,4.0,12.5
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,...,4.0,11.0,BSc,Single,False,False,0.365079,8.0,2.0,6.5

In [152]:
# Sort employees based on custom department order.

order = ['HR', 'IT', 'Finance', 'Sales']

df['department'] = pd.Categorical(df['department'], categories=order, ordered=True)

df.sort_values(by='department')

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before,salary_rank,dept_salary_rank,experience_rank
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,...,10.0,12.0,MBA,Married,False,False,0.317460,7.0,2.0,8.5
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,...,8.0,14.0,MBA,Single,False,False,0.904762,17.0,3.0,15.0
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,...,9.0,12.0,MBA,Married,False,False,0.253968,6.0,1.0,8.5
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,...,12.0,19.0,MBA,Single,False,False,0.952381,18.0,4.0,18.0
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,...,5.0,10.0,BTech,Single,False,False,0.158730,3.0,2.0,2.5
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,...,6.0,18.0,BTech,Married,False,False,0.238095,5.0,3.0,6.5
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,...,9.0,16.0,BTech,Single,False,False,0.650794,14.0,4.0,11.0
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,...,3.0,9.0,BTech,Married,False,False,0.126984,2.0,1.0,4.5
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,...,7.0,15.0,MCA,Single,False,False,0.492063,10.5,2.0,12.5
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,...,4.0,10.0,MCA,Married,False,False,0.507937,12.0,3.0,10.0
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,...,1.0,7.0,MCA,Single,False,False,0.000000,1.0,1.0,1.0
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,...,8.0,15.0,MCA,Married,False,False,0.587302,13.0,4.0,12.5
3,4,Person_4,29.000000,Female,Chennai,0.396825,NaN,3,4.5,True,...,3.0,9.0,BSc,Married,False,False,0.396825,9.0,3.0,4.5
8,9,Person_9,38.684211,Male,Chennai,0.206349,NaN,2,3.5,False,...,2.0,8.0,BSc,Single,False,False,0.206349,4.0,1.0,2.5
9,10,Person_10,28.000000,Female,Bangalore,0.873016,NaN,12,8.0,True,...,11.0,17.0,BA,Married,False,False,0.873016,16.0,3.0,16.0
13,14,Person_14,34.000000,Female,Chennai,1.000000,NaN,15,4.9,True,...,13.0,20.0,BSc,Married,False,False,1.000000,19.0,4.0,19.0
14,15,Person_15,37.000000,Male,Bangalore,0.492063,NaN,9,4.0,False,...,7.0,13.0,BA,Single,False,False,0.492063,10.5,1.0,14.0
18,19,Person_19,30.000000,Male,Chennai,0.365079,NaN,4,3.9,False,...,4.0,11.0,BSc,Single,False,False,0.365079,8.0,2.0,6.5
19,20,Person_20,33.000000,Female,Bangalore,0.777778,NaN,13,4.2,True,...,10.0,11.0,BA,Married,False,False,0.777778,15.0,2.0,17.0

### Section H: replace, map & apply (101–115)

* Performed data transformations using apply, map, and replace functions.
* These techniques support feature engineering and data customization.

In [155]:
# Replace "IT" with "Information Technology".

df['department'] = df['department'].replace('IT', 'Information Technology')
df['department']

0     Information Technology
1                         HR
2                    Finance
3                        NaN
5     Information Technology
6                         HR
7                    Finance
8                        NaN
9                        NaN
10    Information Technology
11                        HR
12                   Finance
13                       NaN
14                       NaN
15    Information Technology
16                        HR
17                   Finance
18                       NaN
19                       NaN
Name: department, dtype: category
Categories (4, object): ['HR' < 'Information Technology' < 'Finance' < 'Sales']

In [156]:
# Replace missing bonus percent with 0.

df['bonus_percent'] = df['bonus_percent'].fillna(0)
df['bonus_percent']

0     10.0
1     12.0
2     15.0
3      9.0
5     18.0
6     14.0
7     10.0
8      8.0
9     17.0
10    16.0
11    12.0
12     7.0
13    20.0
14    13.0
15     9.0
16    19.0
17    15.0
18    11.0
19    11.0
Name: bonus_percent, dtype: float64

In [158]:
# Replace rare education categories with "Other".

rare = df['education'].value_counts()[df['education'].value_counts() < 2].index

df['education'] = df['education'].replace(rare, 'Other')
df['education']

0     BTech
1       MBA
2       MCA
3       BSc
5     BTech
6       MBA
7       MCA
8       BSc
9        BA
10    BTech
11      MBA
12      MCA
13      BSc
14       BA
15    BTech
16      MBA
17      MCA
18      BSc
19       BA
Name: education, dtype: object

In [159]:
# Convert gender into numeric format.

df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})
df['gender']

0     1
1     0
2     1
3     0
5     0
6     1
7     0
8     1
9     0
10    1
11    0
12    1
13    0
14    1
15    0
16    1
17    0
18    1
19    0
Name: gender, dtype: int64

In [160]:
# Replace salary values greater than 1,50,000 with 1,50,000.

df['salary'] = df['salary'].clip(upper=150000)
df['salary']

0     0.158730
1     0.317460
2     0.492063
3     0.396825
5     0.238095
6     0.904762
7     0.507937
8     0.206349
9     0.873016
10    0.650794
11    0.253968
12    0.000000
13    1.000000
14    0.492063
15    0.126984
16    0.952381
17    0.587302
18    0.365079
19    0.777778
Name: salary, dtype: float64

In [161]:
# Create age group column using apply.

df['age_group'] = df['age'].apply(lambda x: 'Young' if x < 30 else 'Middle' if x < 50 else 'Senior')
df['age_group']

0      Young
1     Middle
2     Middle
3      Young
5      Young
6     Middle
7     Senior
8     Middle
9      Young
10    Middle
11    Middle
12     Young
13    Middle
14    Middle
15     Young
16    Middle
17    Middle
18    Middle
19    Middle
Name: age_group, dtype: object

In [162]:
# Create performance label using rating.

df['performance'] = df['rating'].apply(lambda x: 'Low' if x < 3 else 'Average' if x < 4 else 'High')
df['performance']

0        High
1     Average
2        High
3        High
5        High
6     Average
7        High
8     Average
9        High
10       High
11    Average
12    Average
13       High
14       High
15    Average
16       High
17       High
18    Average
19       High
Name: performance, dtype: object

In [163]:
# Create salary slab using lambda.

df['salary_slab'] = df['salary'].apply(lambda x: 'Low' if x < 30000 else 'Medium' if x < 70000 else 'High')
df['salary_slab']

0     Low
1     Low
2     Low
3     Low
5     Low
6     Low
7     Low
8     Low
9     Low
10    Low
11    Low
12    Low
13    Low
14    Low
15    Low
16    Low
17    Low
18    Low
19    Low
Name: salary_slab, dtype: object

In [164]:
# Replace negative values if any with 0.

num_cols = df.select_dtypes(include='number').columns

df[num_cols] = df[num_cols].clip(lower=0)
df[num_cols]

,id,age,gender,salary,experience,rating,projects,leaves_taken,bonus_percent,salary_before,salary_rank,dept_salary_rank,experience_rank
0,1,25.000000,1,0.158730,2,4.2,3.0,5.0,10.0,0.158730,3.0,2.0,2.5
1,2,32.000000,0,0.317460,5,3.8,5.0,10.0,12.0,0.317460,7.0,2.0,8.5
2,3,41.000000,1,0.492063,8,4.5,6.0,7.0,15.0,0.492063,10.5,2.0,12.5
3,4,29.000000,0,0.396825,3,4.5,4.0,3.0,9.0,0.396825,9.0,3.0,4.5
5,6,27.000000,0,0.238095,4,4.1,2.0,6.0,18.0,0.238095,5.0,3.0,6.5
6,7,45.000000,1,0.904762,11,3.9,8.0,8.0,14.0,0.904762,17.0,3.0,15.0
7,8,52.000000,0,0.507937,6,4.3,5.0,4.0,10.0,0.507937,12.0,3.0,10.0
8,9,38.684211,1,0.206349,2,3.5,3.0,2.0,8.0,0.206349,4.0,1.0,2.5
9,10,28.000000,0,0.873016,12,8.0,11.1,11.0,17.0,0.873016,16.0,3.0,16.0
10,11,40.000000,1,0.650794,7,4.4,6.0,9.0,16.0,0.650794,14.0,4.0,11.0
11,12,34.000000,0,0.253968,5,3.7,4.0,9.0,12.0,0.253968,6.0,1.0,8.5
12,13,23.000000,1,0.000000,1,3.3,2.0,1.0,7.0,0.000000,1.0,1.0,1.0
13,14,34.000000,0,1.000000,15,4.9,8.0,13.0,20.0,1.000000,19.0,4.0,19.0
14,15,37.000000,1,0.492063,9,4.0,5.0,7.0,13.0,0.492063,10.5,1.0,14.0
15,16,26.000000,0,0.126984,3,3.6,3.0,3.0,9.0,0.126984,2.0,1.0,4.5
16,17,48.000000,1,0.952381,14,4.6,7.0,12.0,19.0,0.952381,18.0,4.0,18.0
17,18,39.000000,0,0.587302,8,4.1,7.0,8.0,15.0,0.587302,13.0,4.0,12.5
18,19,30.000000,1,0.365079,4,3.9,4.0,4.0,11.0,0.365079,8.0,2.0,6.5
19,20,33.000000,0,0.777778,13,4.2,9.0,10.0,11.0,0.777778,15.0,2.0,17.0

In [167]:
# Create combined city-department column.

df['city_department'] = df['city'].astype(str) + '_' + df['department'].astype(str)
df['city_department']

0     Delhi_Information Technology
1                        Mumbai_HR
2                  Kolkata_Finance
3                      Chennai_nan
5     Delhi_Information Technology
6                        Mumbai_HR
7                  Kolkata_Finance
8                      Chennai_nan
9                    Bangalore_nan
10    Delhi_Information Technology
11                       Mumbai_HR
12                 Kolkata_Finance
13                     Chennai_nan
14                   Bangalore_nan
15    Delhi_Information Technology
16                       Mumbai_HR
17                 Kolkata_Finance
18                     Chennai_nan
19                   Bangalore_nan
Name: city_department, dtype: object

In [168]:
# Replace marital status with binary values.

df['marital_status'] = df['marital_status'].map({'Married': 1, 'Single': 0})
df['marital_status']

0     0
1     1
2     0
3     1
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
Name: marital_status, dtype: int64

In [171]:
# Replace project count outliers using median.

Q1 = df['projects'].quantile(0.25)
Q3 = df['projects'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

median_val = df['projects'].median()

df.loc[(df['projects'] < lower) | (df['projects'] > upper), 'projects'] = median_val
median_val

5.0

In [173]:
# Replace education values using dictionary mapping.

mapping = {'Bachelors': 'UG','Masters': 'PG','PhD': 'Doctorate'}
df['education'] = df['education'].map(mapping)
df['education']

0     NaN
1     NaN
2     NaN
3     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
Name: education, dtype: object

In [175]:
# Apply row-wise condition on salary and experience.

df['category'] = df.apply(
    lambda x: 'High' if (x['salary'] > 70000 and x['experience'] > 5) else 'Low',
    axis=1)

df['category']

0     Low
1     Low
2     Low
3     Low
5     Low
6     Low
7     Low
8     Low
9     Low
10    Low
11    Low
12    Low
13    Low
14    Low
15    Low
16    Low
17    Low
18    Low
19    Low
Name: category, dtype: object

In [176]:
# Create salary after bonus column.

df['salary_after_bonus'] = df['salary'] + (df['salary'] * df['bonus_percent'] / 100)
df['salary_after_bonus']

0     0.174603
1     0.355556
2     0.565873
3     0.432540
5     0.280952
6     1.031429
7     0.558730
8     0.222857
9     1.021429
10    0.754921
11    0.284444
12    0.000000
13    1.200000
14    0.556032
15    0.138413
16    1.133333
17    0.675397
18    0.405238
19    0.863333
Name: salary_after_bonus, dtype: float64

### Section I: GroupBy & Aggregation (116–135)

* Executed group-wise aggregation and analysis for deeper insights.
* This is a critical step in real-world data analytics and reporting.

In [177]:
# Calculate average salary per department.

df.groupby('department', observed=True)['salary'].mean()

department
HR                        0.607143
Information Technology    0.293651
Finance                   0.396825
Name: salary, dtype: float64

In [178]:
# Calculate total projects per department.

df.groupby('department', observed=True)['projects'].sum()

department
HR                        24.0
Information Technology    14.0
Finance                   20.0
Name: projects, dtype: float64

In [179]:
# Calculate average rating per city.

df.groupby('city')['rating'].mean()

city
Bangalore    5.400
Chennai      4.200
Delhi        4.075
Kolkata      4.050
Mumbai       4.000
Name: rating, dtype: float64

In [180]:
# Count employees per department.

df.groupby('department', observed=True)['id'].count()

department
HR                        4
Information Technology    4
Finance                   4
Name: id, dtype: int64

In [181]:
# Calculate department-wise max salary.

df.groupby('department', observed=True)['salary'].max()

department
HR                        0.952381
Information Technology    0.650794
Finance                   0.587302
Name: salary, dtype: float64

In [182]:
# Calculate department-wise min experience.

df.groupby('department', observed=True)['experience'].min()

department
HR                        5
Information Technology    2
Finance                   1
Name: experience, dtype: int64

In [183]:
# Calculate city-wise average bonus percent.

df.groupby('city')['bonus_percent'].mean()

city
Bangalore    13.666667
Chennai      12.000000
Delhi        13.250000
Kolkata      11.750000
Mumbai       14.250000
Name: bonus_percent, dtype: float64

In [185]:
# Group by department and city together.

df.groupby(['department', 'city'], observed=True).size()

department              city
HR                      Mumbai     4
Information Technology  Delhi      4
Finance                 Kolkata    4
dtype: int64

In [186]:
# Find department with highest average salary.

df.groupby('department', observed=True)['salary'].mean().idxmax()

'HR'

In [187]:
# Find city with lowest average rating.

df.groupby('city')['rating'].mean().idxmin()

'Mumbai'

In [190]:
# Group-wise missing value count.

df.groupby('department', observed=True).agg(lambda x: x.isnull().sum())

,id,name,age,gender,city,salary,experience,rating,is_active,projects,...,salary_before,salary_rank,dept_salary_rank,experience_rank,age_group,performance,salary_slab,city_department,category,salary_after_bonus
department,,,,,,,,,,,,,,,,,,,,,
HR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Information Technology,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Finance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [192]:
# Group-wise salary standard deviation.

df.groupby('department', observed=True)['salary'].std()

department
HR                        0.372565
Information Technology    0.242637
Finance                   0.267811
Name: salary, dtype: float64

In [193]:
# Group-wise median salary.

df.groupby('department', observed=True)['salary'].median()

department
HR                        0.611111
Information Technology    0.198413
Finance                   0.500000
Name: salary, dtype: float64

In [194]:
# Calculate department-wise salary range.

df.groupby('department', observed=True)['salary'].agg(lambda x: x.max() - x.min())

department
HR                        0.698413
Information Technology    0.523810
Finance                   0.587302
Name: salary, dtype: float64

In [195]:
# Find top-paid employee per department.

df.loc[df.groupby('department', observed=True)['salary'].idxmax()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,salary_before,salary_rank,dept_salary_rank,experience_rank,age_group,performance,salary_slab,city_department,category,salary_after_bonus
16,17,Person_17,48.0,1,Mumbai,0.952381,HR,14,4.6,False,...,0.952381,18.0,4.0,18.0,Middle,High,Low,Mumbai_HR,Low,1.133333
10,11,Person_11,40.0,1,Delhi,0.650794,Information Technology,7,4.4,True,...,0.650794,14.0,4.0,11.0,Middle,High,Low,Delhi_Information Technology,Low,0.754921
17,18,Person_18,39.0,0,Kolkata,0.587302,Finance,8,4.1,True,...,0.587302,13.0,4.0,12.5,Middle,High,Low,Kolkata_Finance,Low,0.675397

In [196]:
# Find least experienced employee per city.

df.loc[df.groupby('city')['experience'].idxmin()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,salary_before,salary_rank,dept_salary_rank,experience_rank,age_group,performance,salary_slab,city_department,category,salary_after_bonus
14,15,Person_15,37.000000,1,Bangalore,0.492063,NaN,9,4.0,False,...,0.492063,10.5,1.0,14.0,Middle,High,Low,Bangalore_nan,Low,0.556032
8,9,Person_9,38.684211,1,Chennai,0.206349,NaN,2,3.5,False,...,0.206349,4.0,1.0,2.5,Middle,Average,Low,Chennai_nan,Low,0.222857
0,1,Person_1,25.000000,1,Delhi,0.158730,Information Technology,2,4.2,True,...,0.158730,3.0,2.0,2.5,Young,High,Low,Delhi_Information Technology,Low,0.174603
12,13,Person_13,23.000000,1,Kolkata,0.000000,Finance,1,3.3,True,...,0.000000,1.0,1.0,1.0,Young,Average,Low,Kolkata_Finance,Low,0.000000
1,2,Person_2,32.000000,0,Mumbai,0.317460,HR,5,3.8,False,...,0.317460,7.0,2.0,8.5,Middle,Average,Low,Mumbai_HR,Low,0.355556

In [198]:
# Calculate salary contribution percentage per city.

df['city_salary_pct'] = df['salary'] / df['salary'].sum() * 100
df['city_salary_pct']

0      1.706485
1      3.412969
2      5.290102
3      4.266212
5      2.559727
6      9.726962
7      5.460751
8      2.218430
9      9.385666
10     6.996587
11     2.730375
12     0.000000
13    10.750853
14     5.290102
15     1.365188
16    10.238908
17     6.313993
18     3.924915
19     8.361775
Name: city_salary_pct, dtype: float64

In [199]:
# Group-wise normalization of salary.

df['salary_normalized'] = df.groupby('department', observed=True)['salary'].transform(
    lambda x: (x - x.min()) / (x.max() - x.min()))
df['salary_normalized']

0     0.060606
1     0.090909
2     0.837838
3          NaN
5     0.212121
6     0.931818
7     0.864865
8          NaN
9          NaN
10    1.000000
11    0.000000
12    0.000000
13         NaN
14         NaN
15    0.000000
16    1.000000
17    1.000000
18         NaN
19         NaN
Name: salary_normalized, dtype: float64

In [200]:
# Department-wise cumulative employee count.

df['dept_cum_count'] = df.groupby('department', observed=True).cumcount() + 1
df['dept_cum_count']

0     1.0
1     1.0
2     1.0
3     NaN
5     2.0
6     2.0
7     2.0
8     NaN
9     NaN
10    3.0
11    3.0
12    3.0
13    NaN
14    NaN
15    4.0
16    4.0
17    4.0
18    NaN
19    NaN
Name: dept_cum_count, dtype: float64

In [201]:
# Group-wise outlier detection for salary.

def detect_outliers(group):
    Q1 = group['salary'].quantile(0.25)
    Q3 = group['salary'].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return group[(group['salary'] < lower) | (group['salary'] > upper)]

df.groupby('department', observed=True, group_keys=False)\
  .apply(detect_outliers, include_groups=False)

,id,name,age,gender,city,salary,experience,rating,is_active,projects,...,experience_rank,age_group,performance,salary_slab,city_department,category,salary_after_bonus,city_salary_pct,salary_normalized,dept_cum_count
10,11,Person_11,40.0,1,Delhi,0.650794,7,4.4,True,6.0,...,11.0,Middle,High,Low,Delhi_Information Technology,Low,0.754921,6.996587,1.0,3.0
12,13,Person_13,23.0,1,Kolkata,0.000000,1,3.3,True,2.0,...,1.0,Young,Average,Low,Kolkata_Finance,Low,0.000000,0.000000,0.0,3.0

### Section J: Binning using pd.cut / pd.qcut (136–145)

* Implemented binning techniques to convert continuous variables into categorical segments.
* This simplifies analysis and enhances data visualization.

In [202]:
# Create salary bins using pd.cut.

df['salary_bin'] = pd.cut(df['salary'], bins=3)
df['salary_bin']

0     (-0.001, 0.333]
1     (-0.001, 0.333]
2      (0.333, 0.667]
3      (0.333, 0.667]
5     (-0.001, 0.333]
6        (0.667, 1.0]
7      (0.333, 0.667]
8     (-0.001, 0.333]
9        (0.667, 1.0]
10     (0.333, 0.667]
11    (-0.001, 0.333]
12    (-0.001, 0.333]
13       (0.667, 1.0]
14     (0.333, 0.667]
15    (-0.001, 0.333]
16       (0.667, 1.0]
17     (0.333, 0.667]
18     (0.333, 0.667]
19       (0.667, 1.0]
Name: salary_bin, dtype: category
Categories (3, interval[float64, right]): [(-0.001, 0.333] < (0.333, 0.667] < (0.667, 1.0]]

In [203]:
# Label salary bins as Low, Medium, High.

df['salary_bin'] = pd.cut(df['salary'], bins=3, labels=['Low', 'Medium', 'High'])
df['salary_bin']

0        Low
1        Low
2     Medium
3     Medium
5        Low
6       High
7     Medium
8        Low
9       High
10    Medium
11       Low
12       Low
13      High
14    Medium
15       Low
16      High
17    Medium
18    Medium
19      High
Name: salary_bin, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [204]:
# Create age groups using fixed bins.

df['age_group'] = pd.cut(df['age'], bins=[0, 30, 50, 100], labels=['Young', 'Middle', 'Senior'])
df['age_group']

0      Young
1     Middle
2     Middle
3      Young
5      Young
6     Middle
7     Senior
8     Middle
9      Young
10    Middle
11    Middle
12     Young
13    Middle
14    Middle
15     Young
16    Middle
17    Middle
18     Young
19    Middle
Name: age_group, dtype: category
Categories (3, object): ['Young' < 'Middle' < 'Senior']

In [205]:
# Create experience quartiles using pd.qcut.

df['exp_quartile'] = pd.qcut(df['experience'], q=4)
df['exp_quartile']

0     (0.999, 3.5]
1       (3.5, 6.0]
2      (6.0, 10.0]
3     (0.999, 3.5]
5       (3.5, 6.0]
6     (10.0, 15.0]
7       (3.5, 6.0]
8     (0.999, 3.5]
9     (10.0, 15.0]
10     (6.0, 10.0]
11      (3.5, 6.0]
12    (0.999, 3.5]
13    (10.0, 15.0]
14     (6.0, 10.0]
15    (0.999, 3.5]
16    (10.0, 15.0]
17     (6.0, 10.0]
18      (3.5, 6.0]
19    (10.0, 15.0]
Name: exp_quartile, dtype: category
Categories (4, interval[float64, right]): [(0.999, 3.5] < (3.5, 6.0] < (6.0, 10.0] < (10.0, 15.0]]

In [206]:
# Compare bin sizes from cut vs qcut.

# Count from cut
cut_counts = df['salary_bin'].value_counts()

# Count from qcut
qcut_counts = pd.qcut(df['salary'], q=3).value_counts()

cut_counts, qcut_counts

(salary_bin
 Low       7
 Medium    7
 High      5
 Name: count, dtype: int64,
 salary
 (0.587, 1.0]       7
 (-0.001, 0.317]    6
 (0.317, 0.587]     6
 Name: count, dtype: int64)

In [207]:
# Identify highest salary bin employees.

df[df['salary_bin'] == 'High']

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,performance,salary_slab,city_department,category,salary_after_bonus,city_salary_pct,salary_normalized,dept_cum_count,salary_bin,exp_quartile
6,7,Person_7,45.0,1,Mumbai,0.904762,HR,11,3.9,False,...,Average,Low,Mumbai_HR,Low,1.031429,9.726962,0.931818,2.0,High,"(10.0, 15.0]"
9,10,Person_10,28.0,0,Bangalore,0.873016,NaN,12,8.0,True,...,High,Low,Bangalore_nan,Low,1.021429,9.385666,NaN,NaN,High,"(10.0, 15.0]"
13,14,Person_14,34.0,0,Chennai,1.000000,NaN,15,4.9,True,...,High,Low,Chennai_nan,Low,1.200000,10.750853,NaN,NaN,High,"(10.0, 15.0]"
16,17,Person_17,48.0,1,Mumbai,0.952381,HR,14,4.6,False,...,High,Low,Mumbai_HR,Low,1.133333,10.238908,1.000000,4.0,High,"(10.0, 15.0]"
19,20,Person_20,33.0,0,Bangalore,0.777778,NaN,13,4.2,True,...,High,Low,Bangalore_nan,Low,0.863333,8.361775,NaN,NaN,High,"(10.0, 15.0]"

In [208]:
# Create project workload bins.

df['project_workload'] = pd.cut(df['projects'], bins=3, labels=['Low', 'Medium', 'High'])
df['project_workload']

0        Low
1        Low
2     Medium
3        Low
5        Low
6     Medium
7        Low
8        Low
9       High
10    Medium
11       Low
12       Low
13    Medium
14       Low
15       Low
16    Medium
17    Medium
18       Low
19      High
Name: project_workload, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [209]:
# Create bonus percent slabs.

df['bonus_slab'] = pd.cut(df['bonus_percent'], bins=3, labels=['Low', 'Medium', 'High'])
df['bonus_slab']

0        Low
1     Medium
2     Medium
3        Low
5       High
6     Medium
7        Low
8        Low
9       High
10      High
11    Medium
12       Low
13      High
14    Medium
15       Low
16      High
17    Medium
18       Low
19       Low
Name: bonus_slab, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [210]:
# Count employees in each salary bin.

df['salary_bin'].value_counts()

salary_bin
Low       7
Medium    7
High      5
Name: count, dtype: int64

In [212]:
# Analyze average rating per salary bin.

df.groupby('salary_bin', observed=True)['rating'].mean()

salary_bin
Low       3.742857
Medium    4.242857
High      5.120000
Name: rating, dtype: float64